/* DIC Central Sync - Supabase-backed synchronization. Public publishable key only. */
(function(){
const SUPABASE_URL='https://uzoygpyqkdtwwwdqgyff.supabase.co';
const SUPABASE_KEY='sb_publishable_ZDQnm_UMG0q7zHfS7o4V0Q_ljjIqjcG';
const DEVICE_KEY='dic_desktop_device_id_v1'; let client=null,channel=null,profile=null,ready=false,syncing=false;
const deviceId=localStorage.getItem(DEVICE_KEY)||crypto.randomUUID();localStorage.setItem(DEVICE_KEY,deviceId);const baseline=new Map();
const getData=()=>window.__dicGetData?window.__dicGetData():[];
const saveLocal=()=>{try{if(typeof dicSaveMainData==='function')return dicSaveMainData()}catch(_){}return Promise.resolve(false)};
function status(t,k){const e=document.getElementById('dicCloudStatus');if(e)e.textContent=t;const d=document.getElementById('dicCloudDot');if(d)d.className='dic-dot '+(k||'')}
function uid(r){if(r&&r._DIC_ID)return String(r._DIC_ID);const id=crypto.randomUUID();if(r)r._DIC_ID=id;return id}
function payload(r){const p={...r};p._DIC_ID=uid(p);p._UPDATED_AT=p._UPDATED_AT||new Date().toISOString();return p}
function remember(r){const p=payload(r);baseline.set(p._DIC_ID,{...p})}
function addUi(){if(document.getElementById('dicCentralPanel'))return;const s=document.createElement('style');s.textContent=`#dicCentralPanel{position:fixed;right:18px;bottom:18px;z-index:99999;background:#fff;border:1px solid #dfe5ee;border-radius:12px;box-shadow:0 8px 30px #0002;padding:10px 12px;display:flex;align-items:center;gap:7px;font:12px Segoe UI,Arial;max-width:560px}#dicCloudStatus{font-weight:700}.dic-dot{width:9px;height:9px;border-radius:50%;background:#b45309;display:inline-block}.dic-dot.ok{background:#15803d}.dic-dot.bad{background:#b91c1c}#dicCentralPanel button{padding:7px 10px;border-radius:8px;border:0;background:#2563eb;color:#fff;font-weight:700;cursor:pointer}.dic-btn2{background:#475467!important}#dicAuthModal{position:fixed;inset:0;background:#0008;z-index:100000;display:none;align-items:center;justify-content:center}#dicAuthModal .box{width:min(440px,92vw);background:#fff;border-radius:16px;padding:22px;box-shadow:0 20px 60px #0004}#dicAuthModal input{width:100%;margin:7px 0;padding:10px;border:1px solid #dfe5ee;border-radius:9px;box-sizing:border-box}.dic-note{font-size:12px;color:#667085;line-height:1.45}`;document.head.appendChild(s);
const p=document.createElement('div');p.id='dicCentralPanel';p.innerHTML='<span class="dic-dot" id="dicCloudDot"></span><span id="dicCloudStatus">Central Sync: login required</span><button id="dicCloudLogin">Login</button><button id="dicMigrateBtn" class="dic-btn2">Import Old Backup</button><input id="dicMigrateFile" type="file" accept=".json" hidden>';document.body.appendChild(p);
const m=document.createElement('div');m.id='dicAuthModal';m.innerHTML=`<div class="box"><h3 style="margin:0 0 8px">DIC Central Database</h3><div class="dic-note">Use the Supabase account assigned to this DIC workstation. Station permissions are controlled by the DIC profile.</div><input id="dicEmail" type="email" placeholder="Email"><input id="dicPassword" type="password" placeholder="Password"><div style="display:flex;gap:8px;margin-top:12px"><button id="dicSignIn">Sign In</button><button id="dicCloseAuth" class="dic-btn2">Cancel</button></div><div id="dicAuthMsg" class="dic-note" style="margin-top:10px"></div></div>`;document.body.appendChild(m);
document.getElementById('dicCloudLogin').onclick=()=>m.style.display='flex';document.getElementById('dicCloseAuth').onclick=()=>m.style.display='none';document.getElementById('dicSignIn').onclick=signin;document.getElementById('dicMigrateBtn').onclick=()=>{if(!ready){alert('Pehle DIC Central Database login karein.');return}document.getElementById('dicMigrateFile').click()};document.getElementById('dicMigrateFile').onchange=e=>migrateBackup(e)}
async function signin(){const msg=document.getElementById('dicAuthMsg');msg.textContent='Signing in…';try{const {data,error}=await client.auth.signInWithPassword({email:document.getElementById('dicEmail').value.trim(),password:document.getElementById('dicPassword').value});if(error)throw error;document.getElementById('dicAuthModal').style.display='none';await initForUser(data.user)}catch(e){msg.textContent=e.message||String(e);status('Login failed','bad')}}
async function loadProfile(u){const {data,error}=await client.from('dic_profiles').select('*').eq('user_id',u.id).maybeSingle();if(error)throw error;if(!data||!data.is_active)throw new Error('DIC profile is not assigned/active.');profile=data;return data}
async function loadCloud(){const {data,error}=await client.from('dic_cases').select('*').is('deleted_at',null).order('updated_at',{ascending:true});if(error)throw error;const arr=getData();const byId=new Map();(data||[]).forEach(x=>{const r={...(x.data||{})};r._DIC_ID=x.id;r._UPDATED_AT=x.updated_at;byId.set(x.id,r);remember(r)});const local=new Map(arr.map(r=>[uid(r),r]));byId.forEach((r,id)=>{const x=local.get(id);if(!x)arr.push(r);else if(String(x._UPDATED_AT||'')<String(r._UPDATED_AT||''))Object.assign(x,r)});if(profile.role==='agent')for(let i=arr.length-1;i>=0;i--){const r=arr[i];if(String(r.DISTRICT||'')!==String(profile.district||'')||String(r['POLICE STATION']||'')!==String(profile.police_station||''))arr.splice(i,1)}try{render();if(typeof renderCaseCards==='function')renderCaseCards()}catch(_){}await saveLocal();arr.forEach(remember)}
async function upsertRow(r){const p=payload(r);p._UPDATED_AT=new Date().toISOString();r._DIC_ID=p._DIC_ID;r._UPDATED_AT=p._UPDATED_AT;const row={id:p._DIC_ID,district:r.DISTRICT||profile.district||'',police_station:r['POLICE STATION']||profile.police_station||'',case_number:r['L.C NO']||'',title:r['CASE TITLE']||'Mobile Case',data:p,created_by:profile.user_id,updated_by:profile.user_id,device_id:deviceId,updated_at:p._UPDATED_AT,deleted_at:null};const {error}=await client.from('dic_cases').upsert(row,{onConflict:'id'});if(error)throw error;remember(p)}
async function syncChanges(){if(!ready||syncing)return;syncing=true;try{for(const r of getData()){if(profile.role==='agent'&&(String(r.DISTRICT||'')!==String(profile.district||'')||String(r['POLICE STATION']||'')!==String(profile.police_station||'')))continue;const p=payload(r),old=baseline.get(p._DIC_ID);if(!old||JSON.stringify({...old,_UPDATED_AT:undefined})!==JSON.stringify({...p,_UPDATED_AT:undefined}))await upsertRow(r)}await saveLocal();status('Central Sync: live','ok')}catch(e){console.warn(e);status('Central Sync: retry needed','')}finally{syncing=false}}
async function migrateBackup(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x))throw new Error('Invalid JSON backup');const arr=getData(),by=new Map(arr.map(r=>[String(r['L.C NO']||r['FIR / L.C NO']||'').trim().toLowerCase(),r]));let a=0,u=0;for(const r of x){const k=String(r['L.C NO']||r['FIR / L.C NO']||'').trim().toLowerCase(),old=k&&by.get(k);if(old){Object.assign(old,r);u++}else{arr.push({...r});a++}}try{render();if(typeof renderCaseCards==='function')renderCaseCards()}catch(_){}await saveLocal();baseline.clear();await syncChanges();alert('Old backup imported. Added: '+a+' | Updated: '+u)}catch(err){alert('Old backup import failed: '+(err.message||err))}}
async function subscribe(){if(channel)await client.removeChannel(channel);channel=client.channel('dic-cases-live').on('postgres_changes',{event:'*',schema:'public',table:'dic_cases'},p=>{const n=p.new;if(!n?.id)return;const arr=getData();if(n.deleted_at){const i=arr.findIndex(x=>uid(x)===n.id);if(i>=0)arr.splice(i,1);return}const r={...(n.data||{}),_DIC_ID:n.id,_UPDATED_AT:n.updated_at};if(profile.role==='agent'&&(String(r.DISTRICT||'')!==String(profile.district||'')||String(r['POLICE STATION']||'')!==String(profile.police_station||'')))return;const old=arr.find(x=>uid(x)===n.id);if(!old)arr.push(r);else if(String(old._UPDATED_AT||'')<String(n.updated_at||''))Object.assign(old,r);remember(r);try{saveLocal();render();if(typeof renderCaseCards==='function')renderCaseCards()}catch(_){}}).subscribe(s=>{if(s==='SUBSCRIBED')status('Central Sync: live','ok');else if(s==='CHANNEL_ERROR'||s==='TIMED_OUT')status('Central Sync: reconnecting','')})}
function hookSave(){if(typeof window.save!=='function'||window.save.__dicCentralHook)return;const old=window.save;const wrapped=function(){const out=old.apply(this,arguments);setTimeout(syncChanges,200);return out};wrapped.__dicCentralHook=true;window.save=wrapped}
async function initForUser(u){try{await loadProfile(u);ready=true;status('Central Sync: loading…','ok');await loadCloud();hookSave();await syncChanges();await subscribe()}catch(e){ready=false;status(e.message||'Central Sync unavailable','bad');console.warn(e)}}
async function init(){addUi();if(!window.supabase?.createClient){status('Central Sync library missing','bad');return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data}=await client.auth.getSession();if(data?.session?.user)await initForUser(data.session.user);client.auth.onAuthStateChange((_e,s)=>{if(s?.user&&!ready)setTimeout(()=>initForUser(s.user),0)})}
window.dicCentralSync={init,syncChanges};
})();